[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "php artisan migrate --force && php artisan storage:link"
healthcheckPath = "/up"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"
NIXPACKS_PHP_VERSION = "8.4"
