[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
preDeployCommand = "php artisan migrate --force && php artisan storage:link"
startCommand = "php -S 0.0.0.0:$PORT -t public"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"
NIXPACKS_PHP_VERSION = "8.4"
